### PR TITLE
Add composite key support

### PR DESCRIPTION
**Pull request by BrainBlasted**
Previously KeepassGtk did not support databases that used a password
and keyfile. Now through a checkbox users can use both.

### CODE REVIEW

**Comment by BrainBlasted** [comment]
See issue #4

**Comment by FalkAlexander** [comment]
Great! Thank you for implementing this.

**Comment by BrainBlasted** [comment]
Seems like this is a little flaky. Not all databases are working, so please try locally and let me know your thoughts.,

**Comment by FalkAlexander** [comment]
This worked flawlessly in my tests. A problem could be that the library can handle only AES: 256-bit AES-KDF (KDBX 3.1) cipher algorithm. But this is unrelated to this PR.

**Comment by BrainBlasted** [comment]
Thanks. Is that what the latest version of KeepassXC for example uses?

**Comment by FalkAlexander** [comment]
Yes it is, I tested this also with KeepassXC
(+ I am doing many tests with KeepassXC)

**Comment by FalkAlexander** [comment]
I will try to test this more intensely. I can't rule out the possibility that this could be a problem of the library we are using but I hope this is not the case.
Have you created you database with KeepassXC? Any database preferences set?

**Comment by BrainBlasted** [comment]
My databases were created with KeepassXC. Not sure what preferences are 
set right now.

**Pull request merged**
